# Generated by Django 6.0 on 2026-01-14 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatLog',
        ),
    ]
