# Generated by Django 6.0 on 2025-12-20 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_application_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
