# Generated by Django 6.0 on 2026-01-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_achievement_delete_otpverification_delete_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='title',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='year',
        ),
    ]
