# Generated by Django 6.0 on 2025-12-21 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exam_snapshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.studentexam')),
            ],
        ),
    ]
