# Generated by Django 6.0 on 2025-12-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='passing_marks',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
    ]
