# Generated by Django 6.0 on 2025-12-23 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_passing_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=20, unique=True)),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('is_pass', models.BooleanField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('student_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.studentexam')),
            ],
        ),
    ]
