# Generated by Django 6.0 on 2025-12-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
