# Generated by Django 6.0 on 2025-12-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examresult_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
