"""
Django settings for ExamPlatform project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b6l-*e#si+-1a#8=o&+)$4l7$xx=)od(^ou)8nwlh$m9f&*tqt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'exams.apps.ExamsConfig',
    'django.contrib.sites',
    'rest_framework',
    'accounts',
]

SITE_ID = 1

USE_HTTPS = False


# from django.contrib.sites.models import Site

# site = Site.objects.get(id=1)
# site.domain = "127.0.0.1:8000"  #deployement nanater fhkt he chnage kr 
# site.name = "Smart Exam Local"
# site.save()



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ExamPlatform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'accounts.context_processors.logged_user',
                'exams.context_processors.current_user',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ExamPlatform.wsgi.application'

AUTH_USER_MODEL = 'accounts.User'



# jazzmin settings
JAZZMIN_SETTINGS = {
    "site_title": "Smart Exam Admin",
    "site_header": "Smart Exam Platform",
    "site_brand": "Smart Exam",
    "welcome_sign": "Welcome to Smart Exam Admin",
    "site_logo": None,  # path to logo if any
    "login_logo": None,
    "show_ui_builder": True,
    "topmenu_links": [
        {"name": "Dashboard", "url": "/admin/dashboard/", "permissions": ["auth.view_user"]},
        {"model": "accounts.User"},
        {"model": "exams.Exam"},
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "exams": "fas fa-file-alt",
        "accounts": "fas fa-user",
    },
    "order_with_respect_to": ["auth", "accounts", "exams"],
    "related_modal_active": True,
}




# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'Exam',
        'USER': 'postgres',
        'PASSWORD': 'Pravin6670@#$', 
        'HOST': 'localhost',        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# SMTP Configurations

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'pravinsaindane2005@gmail.com'
EMAIL_HOST_PASSWORD = 'lbyy wntz qdti nxve'   

DEFAULT_FROM_EMAIL = 'IMRD Tech Club <pravinsaindane2005@gmail.com>'



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/





# media files (student profile pics, uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# settings.py
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]  # dev mode
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")    # collectstatic साठी



STATICFILES_DIRS = [
    BASE_DIR / "static",   # optional (global)
]






# jwt authentication 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


LOGIN_URL = 'login'
